;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Context: internal
;;
;; Purpose:
;; - Handle calls originating from internal SIP phones.
;; - Route extension-to-extension calls.
;; - Forward PSTN calls to the Telnyx outbound context.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[internal]

; Internal Extensions
exten => 1000,1,Dial(PJSIP/1000)
exten => 2000,1,Dial(PJSIP/2000)

; Outbound PSTN
; Pattern:
; 1 = Country Code
; N = 2-9
; X = 0-9
; Example: 1315273XXXX
exten => _1NXXNXXXXXX,1,Goto(To-Telnyx,${EXTEN},1)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Inbound PSTN Calls from Telnyx
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[from-telnyx]
exten => _X.,1,NoOp(===== Incoming Call From Telnyx =====)
 same => n,NoOp(CallerID: ${CALLERID(num)})
 same => n,NoOp(Dialed Number: ${EXTEN})
 same => n,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Outbound  PSTN Calls  to Telnyx
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[To-Telnyx]
exten => _1NXXNXXXXXX,1,NoOp(===== Outbound PSTN Call =====)
 same => n,NoOp(Calling Number: ${CALLERID(num)})
 same => n,NoOp(Dialed Number: ${EXTEN})
 same => n,Set(CALLERID(num)=1315273XXXX) ;Purchased Telnyx number caller ID
 same => n,Dial(PJSIP/${EXTEN}@Carrier-Telnyx) ;Route the call Via Carrier-Telnyx trunk
 same => n,Hangup()








 
