[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
; Azure public IP
external_signaling_address=
external_media_address=

; Azure VNet
local_net=

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Auth objects
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[1000]
type=auth
auth_type=userpass
username=
password=

[2000]
type=auth
auth_type=userpass
username=
password=


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; AORs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[1000]
type=aor
max_contacts=1
remove_existing=yes

[2000]
type=aor
max_contacts=1


remove_existing=yes

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Phones
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[1000]
type=endpoint
auth=1000
aors=1000
context=internal
transport=transport-udp
disallow=all
allow=ulaw

[2000]
type=endpoint
auth=2000
aors=2000
context=internal
transport=transport-udp
disallow=all
allow=ulaw

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Carrier : Telnyx SIP Trunk
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Carrier : Telnyx SIP Trunk
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


[Carrier-Telnyx]
type=endpoint
transport=transport-udp
context=from-telnyx
aors=Carrier-Telnyx-AOR
identify_by=ip
disallow=all
allow=ulaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes


[Carrier-Telnyx-AOR]
type=aor
contact=sip:sip.telnyx.com:5060
qualify_frequency=60

[Carrier-Telnyx-Identify]
type=identify
endpoint=Carrier-Telnyx
match=sip.telnyx.com
match=
match=





