[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Auth objects
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=Cisco123!


[2000-auth]
type=auth
auth_type=userpass
username=2000
password=Cisco123!




;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; AORs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[1000-aor]
type=aor
max_contacts=1

[2000-aor]
type=aor
max_contacts=1


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Phones
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[phone-1000]
type=endpoint
auth=1000-auth
aors=1000-aor
context=internal
transport=transport-udp
disallow=all
allow=ulaw

[phone-2000]
type=endpoint
auth=2000-auth
aors=2000-aor
context=internal
transport=transport-udp
disallow=all
allow=ulaw

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Carrier : Telnyx SIP Trunk
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Carrier-Telnyx]
type=endpoint
transport=transport-udp
context=from-telnyx
aors=Carrier-Telnyx-AOR
identify_by=ip
disallow=all
allow=ulaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[Carrier-Telnyx-AOR]
type=aor
contact=sip:sip.telnyx.com:5060
qualify_frequency=60

[Carrier-Telnyx-Identify]
type=identify
endpoint=Carrier-Telnyx
match=sip.telnyx.com
